
### 🔹 LISTAR PROPIEDADES
GET http://localhost:3000/api/v1/properties

### 🔹 CREAR PROPIEDAD
POST http://localhost:3000/api/v1/properties
Content-Type: application/json

{
  "title": "Casa en Cartagena",
  "location": "Cartagena",
  "pricePerNight": 200,
  "maxDaysPerYear": 60
}

### 🔹 OBTENER PROPIEDAD
GET http://localhost:3000/api/v1/properties/1

### 🔹 ACTUALIZAR COMPLETO (PUT)
PUT http://localhost:3000/api/v1/properties/1
Content-Type: application/json

{
  "title": "Casa actualizada",
  "location": "Cartagena",
  "pricePerNight": 250,
  "maxDaysPerYear": 80
}

### 🔹 ACTUALIZAR PARCIAL (PATCH)
PATCH http://localhost:3000/api/v1/properties/1
Content-Type: application/json

{
  "pricePerNight": 300
}

### 🔹 ELIMINAR
DELETE http://localhost:3000/api/v1/properties/1

### 🔹 CREAR LICENCIA
POST http://localhost:3000/api/v1/properties/1/license
Content-Type: application/json

{
  "number": "LIC-123",
  "valid": true
}

### 🔹 OBTENER LICENCIA
GET http://localhost:3000/api/v1/properties/1/license

### 🔹 CREAR RESERVA (VALIDA)
POST http://localhost:3000/api/v1/properties/1/bookings
Content-Type: application/json

{
  "guestName": "Ana",
  "days": 5
}

### 🔹 ERROR: RESERVA SIN LICENCIA
POST http://localhost:3000/api/v1/properties/2/bookings
Content-Type: application/json

{
  "guestName": "Juan",
  "days": 5
}

### 🔹 ERROR: EXCESO DE DÍAS
POST http://localhost:3000/api/v1/properties/1/bookings
Content-Type: application/json

{
  "guestName": "Pedro",
  "days": 100
}

### 🔹 CREAR INCIDENCIA
POST http://localhost:3000/api/v1/properties/1/incidents
Content-Type: application/json

{
  "description": "Ruido excesivo"
}

### 🔹 LISTAR INCIDENCIAS
GET http://localhost:3000/api/v1/properties/1/incidents
